name: ğŸš€ Deploy Vite App to VPS

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“¦ Checkout Code
        uses: actions/checkout@v3

      - name: ğŸš€ Deploy to VPS via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.REPO_SSH_KEY}}
          port: 22
          script: |
            echo "ğŸ” Switching to app directory..."
            cd /home/ubuntu/fe_apps/Fourteen_Vite

            echo "ğŸ“¥ Pulling latest changes from GitHub..."
            git reset --hard
            git pull origin main

            echo "ğŸ“¦ Installing dependencies..."
            npm install

            echo "ğŸ›  Building the Vite app..."
            npm run build

            echo "âœ… Deployment complete."
